import { normalizeLimitPercent, normalizeLimitType } from "./rate-calculator.js";

/**
 * Parse Betaflight CLI dump format
 * @param {string} text - CLI dump text
 * @returns {Object} Parsed settings as key-value pairs
 */
export function parseCLI(text) {
  // Use a null-prototype object so `key in settings` only checks parsed keys,
  // never inherited properties like `constructor` or `toString`.
  const settings = Object.create(null);
  const lines = text.split("\n");

  for (const line of lines) {
    // Match pattern: [set] parameter_name = value
    // Support optional 'set' prefix and varied spacing
    const match = line.match(/^\s*(?:set\s+)?([a-z_]+)\s*=\s*(.+?)\s*$/i);
    if (match) {
      const key = match[1].toLowerCase();
      const value = match[2].trim();
      // Store first occurrence only. Betaflight "dump rates" outputs every
      // rateprofile in sequence; keeping the first means we always import
      // rateprofile 0 instead of accidentally importing a later profile's
      // (often zeroed-out) values.
      if (!(key in settings)) {
        settings[key] = value;
      }
    }
  }

  return settings;
}

/**
 * Generate Betaflight CLI commands from a profile.
 *
 * Emits the correct parameter name for max rate based on the profile's
 * ratesType:
 *   ACTUAL     → roll_srate  (speed in deg/s)
 *   BETAFLIGHT → roll_rate   (super rate 0-100)
 *
 * @param {Object} profile - Profile object with rates and throttle settings
 * @returns {string} CLI commands
 */
export function generateCLI(profile) {
  const ratesType = (profile.ratesType || "ACTUAL").toUpperCase();
  // ACTUAL rates → srate parameter; BETAFLIGHT → rate parameter
  const maxRateParam = ratesType === "BETAFLIGHT" ? "rate" : "srate";

  const commands = [
    "# Betaflight Rate Profile Configuration",
    "# Generated by FPV Rate Profile Comparison Tool",
    "",
  ];

  if (profile.name) {
    commands.push(`# Profile: ${profile.name}`);
    commands.push("");
  }

  commands.push(
    "# Rate Type",
    `set rates_type = ${ratesType}`,
    "",
    "# Roll Rates",
    `set roll_rc_rate = ${profile.rates.roll.center}`,
    `set roll_${maxRateParam} = ${profile.rates.roll.maxRate}`,
    `set roll_expo = ${profile.rates.roll.expo}`,
    "",
    "# Pitch Rates",
    `set pitch_rc_rate = ${profile.rates.pitch.center}`,
    `set pitch_${maxRateParam} = ${profile.rates.pitch.maxRate}`,
    `set pitch_expo = ${profile.rates.pitch.expo}`,
    "",
    "# Yaw Rates",
    `set yaw_rc_rate = ${profile.rates.yaw.center}`,
    `set yaw_${maxRateParam} = ${profile.rates.yaw.maxRate}`,
    `set yaw_expo = ${profile.rates.yaw.expo}`,
    "",
    "# Throttle",
    `set thr_mid = ${profile.throttle.mid}`,
    `set thr_expo = ${profile.throttle.expo}`,
    `set throttle_limit_type = ${normalizeLimitType(profile.throttle.limitType)}`,
    `set throttle_limit_percent = ${normalizeLimitPercent(profile.throttle.limitPercent)}`,
    "",
    "save",
  );

  return commands.join("\n");
}
