import { normalizeLimitPercent, normalizeLimitType } from "./rate-calculator.js";

/**
 * Parse assignment lines from a slice of CLI output into a flat settings map.
 * Accepts both `set key = value` lines and bare `key = value` lines (the
 * `set` prefix is optional). Uses a null-prototype object so key-in checks
 * never match inherited properties.
 * @param {string[]} lines
 * @returns {Object}
 */
function parseSection(lines) {
  const settings = Object.create(null);
  for (const line of lines) {
    const match = line.match(/^\s*(?:set\s+)?([a-z_]+)\s*=\s*(.+?)\s*$/i);
    if (match) {
      const key = match[1].toLowerCase();
      if (!(key in settings)) {
        settings[key] = match[2].trim();
      }
    }
  }
  return settings;
}

/**
 * Parse all rateprofile sections from a full Betaflight CLI dump.
 *
 * A `dump rates` (or `diff all`) output contains one section per rateprofile
 * slot, each preceded by a `rateprofile N` header line. This function splits
 * on those boundaries and returns an array of flat settings maps (same shape as
 * parseCLI), one per rateprofile found, in the order they appear in the dump.
 * Sections that contain no recognisable `set` commands are omitted.
 *
 * @param {string} text - Full CLI dump text
 * @returns {Array<Object>} One settings map per non-empty rateprofile section
 */
export function parseAllRateProfiles(text) {
  const profiles = [];
  const lines = text.split(/\r?\n/);

  /** @type {string[]|null} Lines accumulated for the current section, or null if not yet inside one. */
  let sectionLines = null;

  for (const line of lines) {
    if (/^rateprofile\s+\d+/i.test(line.trim())) {
      // Flush the previous section (if any), skipping empty ones.
      if (sectionLines !== null) {
        const settings = parseSection(sectionLines);
        if (Object.keys(settings).length > 0) profiles.push(settings);
      }
      sectionLines = [];
      continue;
    }
    if (sectionLines !== null) sectionLines.push(line);
  }

  // Flush the final section.
  if (sectionLines !== null) {
    const settings = parseSection(sectionLines);
    if (Object.keys(settings).length > 0) profiles.push(settings);
  }

  return profiles;
}

/**
 * Parse Betaflight CLI dump format
 * @param {string} text - CLI dump text
 * @returns {Object} Parsed settings as key-value pairs
 */
export function parseCLI(text) {
  // Use a null-prototype object so `key in settings` only checks parsed keys,
  // never inherited properties like `constructor` or `toString`.
  const settings = Object.create(null);
  const lines = text.split("\n");

  for (const line of lines) {
    // Match pattern: [set] parameter_name = value
    // Support optional 'set' prefix and varied spacing
    const match = line.match(/^\s*(?:set\s+)?([a-z_]+)\s*=\s*(.+?)\s*$/i);
    if (match) {
      const key = match[1].toLowerCase();
      const value = match[2].trim();
      // Store first occurrence only. Betaflight "dump rates" outputs every
      // rateprofile in sequence; keeping the first means we always import
      // rateprofile 0 instead of accidentally importing a later profile's
      // (often zeroed-out) values.
      if (!(key in settings)) {
        settings[key] = value;
      }
    }
  }

  return settings;
}

/**
 * Generate Betaflight CLI commands from a profile.
 *
 * Both ACTUAL and BETAFLIGHT rate types use `roll_srate` / `pitch_srate` /
 * `yaw_srate` in the Betaflight 4.x CLI.  The value semantics differ:
 *   ACTUAL     → roll_srate  = max rate in deg/s  (200-2000)
 *   BETAFLIGHT → roll_srate  = super rate percent (0-100)
 *
 * @param {Object} profile - Profile object with rates and throttle settings
 * @returns {string} CLI commands
 */
export function generateCLI(profile) {
  const ratesType = (profile.ratesType || "ACTUAL").toUpperCase();
  // Both ACTUAL and BETAFLIGHT types use the srate parameter name in modern BF.
  const maxRateParam = "srate";

  // For ACTUAL rates, the Betaflight CLI stores the max-rate value as 1/10 deg/s
  // (a UINT8 0-255 that the firmware multiplies by 10 to get deg/s).  The profile
  // object stores maxRate in deg/s, so divide by 10 before emitting.
  // For BETAFLIGHT, maxRate is the super-rate percent (0-100); no scaling needed.
  const encodeSrate = (v) => ratesType === "ACTUAL" ? Math.round(v / 10) : v;

  const commands = [
    "# Betaflight Rate Profile Configuration",
    "# Generated by FPV Rate Profile Comparison Tool",
    "",
  ];

  if (profile.name) {
    commands.push(`# Profile: ${profile.name}`);
    commands.push("");
  }

  commands.push(
    "# Rate Type",
    `set rates_type = ${ratesType}`,
    "",
    "# Roll Rates",
    `set roll_rc_rate = ${profile.rates.roll.center}`,
    `set roll_${maxRateParam} = ${encodeSrate(profile.rates.roll.maxRate)}`,
    `set roll_expo = ${profile.rates.roll.expo}`,
    "",
    "# Pitch Rates",
    `set pitch_rc_rate = ${profile.rates.pitch.center}`,
    `set pitch_${maxRateParam} = ${encodeSrate(profile.rates.pitch.maxRate)}`,
    `set pitch_expo = ${profile.rates.pitch.expo}`,
    "",
    "# Yaw Rates",
    `set yaw_rc_rate = ${profile.rates.yaw.center}`,
    `set yaw_${maxRateParam} = ${encodeSrate(profile.rates.yaw.maxRate)}`,
    `set yaw_expo = ${profile.rates.yaw.expo}`,
    "",
    "# Throttle",
    `set thr_mid = ${profile.throttle.mid}`,
    `set thr_expo = ${profile.throttle.expo}`,
    `set throttle_limit_type = ${normalizeLimitType(profile.throttle.limitType)}`,
    `set throttle_limit_percent = ${normalizeLimitPercent(profile.throttle.limitPercent)}`,
    "",
    "save",
  );

  return commands.join("\n");
}
